name: where_im_at
description: "A new Flutter project."
publish_to: "none"
version: 1.2.1

environment:
  sdk: ^3.6.1
  flutter: ">=3.27.3"

dependencies:
  adaptive_dialog: ^2.4.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.3.0
  dio: ^5.7.0
  envied: ^1.0.1
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_storage: ^12.4.0
  flutter:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_bloc: ^9.0.0
  flutter_cache_manager: ^3.4.1
  flutter_html: ^3.0.0-beta.2
  flutter_keyboard_visibility_temp_fork: ^0.1.4
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.8.0
  flutter_map_cached_tile_provider:
    git:
      url: https://github.com/physia/kflutter.git
      path: flutter_map_cached_tile_provider
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.17
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.6.3
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: any
  latlong2: ^0.9.1
  pretty_dio_logger: ^1.4.0
  skeletonizer: ^1.4.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  dart_mappable_builder: ^4.3.0
  envied_generator: ^1.0.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/splash/
    - assets/svg/

flutter_native_splash:
  color: "#F2F3F0"
  image: "assets/splash/splash.png"
  android_12:
    color: "#F2F3F0"
    image: "assets/splash/splash_android_12.png"
