name: Create release
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-android:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1 # Must be the same with the one in pubspec.yaml

      - name: Configure environment and secrets
        run: |
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env
          echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 --decode > lib/firebase_options.dart
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

      - name: Download dependencies
        run: flutter pub get

      - name: Run build runner and generate localization files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter gen-l10n

      - name: Build Android
        run: flutter build apk --release --obfuscate --split-debug-info=build/app/outputs/symbols --build-number=${{ github.run_number }} --split-per-abi

      - name: Upload Android build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: build/app/outputs/flutter-apk/*.apk

      - name: Upload Android debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-symbols
          path: build/app/outputs/symbols
          retention-days: 1

  build-ios:
    name: Build IPA
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1 # Must be the same with the one in pubspec.yaml

      - name: Configure environment and secrets
        run: |
          echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env
          echo "${{ secrets.FIREBASE_OPTIONS }}" | base64 --decode > lib/firebase_options.dart
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Clean and get dependencies
        run: flutter clean && flutter pub get

      - name: Run build runner and generate localization files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter gen-l10n

      - name: Build iOS
        run: flutter build ios --release --no-codesign --obfuscate --split-debug-info=build/ios/outputs/symbols --build-number=${{ github.run_number }}

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app.ipa Payload

      - name: Upload iOS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-artifacts
          path: build/ios/iphoneos/app.ipa

      - name: Upload iOS debug symbols
        uses: actions/upload-artifact@v4
        with:
          name: ios-debug-symbols
          path: build/ios/outputs/symbols
          retention-days: 1

  create-release:
    name: Create Release
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Read latest version from CHANGELOG
        id: changelog
        shell: bash
        run: |
          LATEST_VERSION=$(grep -m1 "^## \[" CHANGELOG.md | sed -E 's/## \[(.*)\].*/\1/')
          if [ -z "$LATEST_VERSION" ]; then
            echo "No version found in CHANGELOG.md"
            exit 1
          fi

          # Extract content between the current and the next version or until the end of the file
          CHANGELOG_CONTENT=$(awk "/^## \[$LATEST_VERSION\]/ {flag=1; next} /^## \[/ {flag=0} flag {print}" CHANGELOG.md)

          if [ -z "$CHANGELOG_CONTENT" ]; then
            echo "No changelog content found for version $LATEST_VERSION"
            exit 1
          fi

          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo 'content<<EOF' >> $GITHUB_OUTPUT
          echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          prerelease: false
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "android-artifacts/*.apk,ios-artifacts/app.ipa"
          body: |
            ${{ steps.changelog.outputs.content }}

            > [!WARNING]
            > The IPA file is unsigned and intended solely for testing purposes. It is not eligible for App Store submission. It requires a developer account and Xcode to install and run on a device.
