name: Run tests

on:
  push:
    branches-ignore:
      - "v*"
    tags-ignore:
      - "v*"
  workflow_dispatch:

jobs:
  verification:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.3 # Must be the same with the one in pubspec.yaml

      - name: Download dependencies
        run: flutter pub get

      - name: Configure environment
        run: echo "${{ secrets.ENVIRONMENT }}" | base64 --decode > .env

      - name: Run build runner and generate localization files
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter gen-l10n

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Install and configure FlutterFire CLI
        run: |
          dart pub global activate flutterfire_cli
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/service-account.json"
          flutterfire configure \
            --project=where-i-m-at-app \
            --platforms=ios \
            --ios-bundle-id=com.sunadriann.whereimat \
            --no-apply \
            --yes

      - name: Analyze
        run: flutter analyze --no-pub

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random
